config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :reviews, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country, :presence => true
  validates :description, :presence => true
  before_save :upcase_first_letter

  scope :mostReviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}
  scope :mostRecent, -> {(
    order(created_at: :desc).limit(3)
    )}
  scope :localProducts, -> { where(country: 'United States')}

  define_method(:upcase_first_letter) do
    self.name =  self.name.slice(0,1).capitalize + self.name.slice(1..-1)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  validates :author, :presence => true
  validates :content_body, {:presence => true, length: { in: 50..250 }}
  validates :rating, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to request.env['HTTP_REFERER']
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Oops! Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Molle:400i|PT+Sans" rel="stylesheet">
    <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Home', products_path, {class: "navbar-brand"} %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/#about">About</a></li>
          <li><a href="/#products">Products</a></li>
          <li><a href="/#popular">Popular</a></li>
          <li><a href="/#new">New</a></li>
        </ul>
      </div>
    </nav>
    <div class="main">
      <%= yield %>
      <div class="container">
        <div class="row">
          <div class="col-sm-4">

          </div>
          <div class="col-sm-3">
            <h2>Location:</h2>
            <p>2340 NE Sandy Boulevard at 24th</p>
            <p>Portland, OR 97232</p>
            <p>503-232-1010</p>
          </div>
          <div class="col-sm-3">
            <h2>Hours:</h2>
            <p>Daily</p>
            <p>9:30a to 7:00p</p>
          </div>
          <div class="col-sm-4">

          </div>
        </div>

        <div class="row" id="social">
          <%= image_tag "email.png" %>
          <%= image_tag "facebook.png" %>
          <%= image_tag "twitter.png" %>
          <%= image_tag "instagram.png" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render('layouts/errors', :object => @product) %>

<%= form_for @product do |f| %>
  <%= f.label :product_name, {class: "form-group"}, id: 'Name' %>
  <%= f.text_field :name, {class: "form-control"} %>
  <%= f.label :cost, {class: "form-group"}, id: 'Cost'  %>
  <%= f.number_field :cost, {class: "form-control"} %>
  <%= f.label :country, {class: "form-group"}, id: 'Country' %>
  <%= f.select :country, options_for_select([
  [ 'Afghanistan',  'Afghanistan'],
  [ 'Aland Islands',  'Aland Islands'],
  [ 'Albania',  'Albania'],
  [ 'Algeria',  'Algeria'],
  [ 'American Samoa',  'American Samoa'],
  [ 'AndorrA',  'AndorrA'],
  [ 'Angola',  'Angola'],
  [ 'Anguilla',  'Anguilla'],
  [ 'Antarctica',  'Antarctica'],
  [ 'Antigua and Barbuda',  'Antigua and Barbuda'],
  [ 'Argentina',  'Argentina'],
  [ 'Armenia',  'Armenia'],
  [ 'Aruba',  'Aruba'],
  [ 'Australia',  'Australia'],
  [ 'Austria',  'Austria'],
  [ 'Azerbaijan',  'Azerbaijan'],
  [ 'Bahamas',  'Bahamas'],
  [ 'Bahrain',  'Bahrain'],
  [ 'Bangladesh',  'Bangladesh'],
  [ 'Barbados',  'Barbados'],
  [ 'Belarus',  'Belarus'],
  [ 'Belgium',  'Belgium'],
  [ 'Belize',  'Belize'],
  [ 'Benin',  'Benin'],
  [ 'Bermuda',  'Bermuda'],
  [ 'Bhutan',  'Bhutan'],
  [ 'Bolivia',  'Bolivia'],
  [ 'Bosnia and Herzegovina',  'Bosnia and Herzegovina'],
  [ 'Botswana',  'Botswana'],
  [ 'Bouvet Island',  'Bouvet Island'],
  [ 'Brazil',  'Brazil'],
  [ 'British Indian Ocean Territory',  'British Indian Ocean Territory'],
  [ 'Brunei Darussalam',  'Brunei Darussalam'],
  [ 'Bulgaria',  'Bulgaria'],
  [ 'Burkina Faso',  'Burkina Faso'],
  [ 'Burundi',  'Burundi'],
  [ 'Cambodia',  'Cambodia'],
  [ 'Cameroon',  'Cameroon'],
  [ 'Canada',  'Canada'],
  [ 'Cape Verde',  'Cape Verde'],
  [ 'Cayman Islands',  'Cayman Islands'],
  [ 'Central African Republic',  'Central African Republic'],
  [ 'Chad',  'Chad'],
  [ 'Chile',  'Chile'],
  [ 'China',  'China'],
  [ 'Christmas Island',  'Christmas Island'],
  [ 'Cocos (Keeling) Islands',  'Cocos (Keeling) Islands'],
  [ 'Colombia',  'Colombia'],
  [ 'Comoros',  'Comoros'],
  [ 'Congo',  'Congo'],
  [ 'Cook Islands',  'Cook Islands'],
  [ 'Costa Rica',  'Costa Rica'],
  [ 'Cote DIvoire',  'Cote DIvoire'],
  [ 'Croatia',  'Croatia'],
  [ 'Cuba',  'Cuba'],
  [ 'Cyprus',  'Cyprus'],
  [ 'Czech Republic',  'Czech Republic'],
  [ 'Denmark',  'Denmark'],
  [ 'Djibouti',  'Djibouti'],
  [ 'Dominica',  'Dominica'],
  [ 'Dominican Republic',  'Dominican Republic'],
  [ 'Ecuador',  'Ecuador'],
  [ 'Egypt',  'Egypt'],
  [ 'El Salvador',  'El Salvador'],
  [ 'Equatorial Guinea',  'Equatorial Guinea'],
  [ 'Eritrea',  'Eritrea'],
  [ 'Estonia',  'Estonia'],
  [ 'Ethiopia',  'Ethiopia'],
  [ 'Falkland Islands (Malvinas)',  'Falkland Islands (Malvinas)'],
  [ 'Faroe Islands',  'Faroe Islands'],
  [ 'Fiji',  'Fiji'],
  [ 'Finland',  'Finland'],
  [ 'France',  'France'],
  [ 'French Guiana',  'French Guiana'],
  [ 'French Polynesia',  'French Polynesia'],
  [ 'French Southern Territories',  'French Southern Territories'],
  [ 'Gabon',  'Gabon'],
  [ 'Gambia',  'Gambia'],
  [ 'Georgia',  'Georgia'],
  [ 'Germany',  'Germany'],
  [ 'Ghana',  'Ghana'],
  [ 'Gibraltar',  'Gibraltar'],
  [ 'Greece',  'Greece'],
  [ 'Greenland',  'Greenland'],
  [ 'Grenada',  'Grenada'],
  [ 'Guadeloupe',  'Guadeloupe'],
  [ 'Guam',  'Guam'],
  [ 'Guatemala',  'Guatemala'],
  [ 'Guernsey',  'Guernsey'],
  [ 'Guinea',  'Guinea'],
  [ 'Guinea-Bissau',  'Guinea-Bissau'],
  [ 'Guyana',  'Guyana'],
  [ 'Haiti',  'Haiti'],
  [ 'Heard Island and Mcdonald Islands',  'Heard Island and Mcdonald Islands'],
  [ 'Holy See (Vatican City State)',  'Holy See (Vatican City State)'],
  [ 'Honduras',  'Honduras'],
  [ 'Hong Kong',  'Hong Kong'],
  [ 'Hungary',  'Hungary'],
  [ 'Iceland',  'Iceland'],
  [ 'India',  'India'],
  [ 'Indonesia',  'Indonesia'],
  [ 'Iran',  'Iran'],
  [ 'Iraq',  'Iraq'],
  [ 'Ireland',  'Ireland'],
  [ 'Isle of Man',  'Isle of Man'],
  [ 'Israel',  'Israel'],
  [ 'Italy',  'Italy'],
  [ 'Jamaica',  'Jamaica'],
  [ 'Japan',  'Japan'],
  [ 'Jersey',  'Jersey'],
  [ 'Jordan',  'Jordan'],
  [ 'Kazakhstan',  'Kazakhstan'],
  [ 'Kenya',  'Kenya'],
  [ 'Kiribati',  'Kiribati'],
  [ 'Korea',  'Korea'],
  [ 'Kuwait',  'Kuwait'],
  [ 'Kyrgyzstan',  'Kyrgyzstan'],
  [ 'Lao Peoples Democratic Republic',  'Lao Peoples Democratic Republic'],
  [ 'Latvia',  'Latvia'],
  [ 'Lebanon',  'Lebanon'],
  [ 'Lesotho',  'Lesotho'],
  [ 'Liberia',  'Liberia'],
  [ 'Libyan Arab Jamahiriya',  'Libyan Arab Jamahiriya'],
  [ 'Liechtenstein',  'Liechtenstein'],
  [ 'Lithuania',  'Lithuania'],
  [ 'Luxembourg',  'Luxembourg'],
  [ 'Macao',  'Macao'],
  [ 'Macedonia',  'Macedonia'],
  [ 'Madagascar',  'Madagascar'],
  [ 'Malawi',  'Malawi'],
  [ 'Malaysia',  'Malaysia'],
  [ 'Maldives',  'Maldives'],
  [ 'Mali',  'Mali'],
  [ 'Malta',  'Malta'],
  [ 'Marshall Islands',  'Marshall Islands'],
  [ 'Martinique',  'Martinique'],
  [ 'Mauritania',  'Mauritania'],
  [ 'Mauritius',  'Mauritius'],
  [ 'Mayotte',  'Mayotte'],
  [ 'Mexico',  'Mexico'],
  [ 'Micronesia',  'Micronesia'],
  [ 'Moldova',  'Moldova'],
  [ 'Monaco',  'Monaco'],
  [ 'Mongolia',  'Mongolia'],
  [ 'Montserrat',  'Montserrat'],
  [ 'Morocco',  'Morocco'],
  [ 'Mozambique',  'Mozambique'],
  [ 'Myanmar',  'Myanmar'],
  [ 'Namibia',  'Namibia'],
  [ 'Nauru',  'Nauru'],
  [ 'Nepal',  'Nepal'],
  [ 'Netherlands',  'Netherlands'],
  [ 'Netherlands Antilles',  'Netherlands Antilles'],
  [ 'New Caledonia',  'New Caledonia'],
  [ 'New Zealand',  'New Zealand'],
  [ 'Nicaragua',  'Nicaragua'],
  [ 'Niger',  'Niger'],
  [ 'Nigeria',  'Nigeria'],
  [ 'Niue',  'Niue'],
  [ 'Norfolk Island',  'Norfolk Island'],
  [ 'Northern Mariana Islands',  'Northern Mariana Islands'],
  [ 'Norway',  'Norway'],
  [ 'Oman',  'Oman'],
  [ 'Pakistan',  'Pakistan'],
  [ 'Palau',  'Palau'],
  [ 'Palestinian Territory',  'Palestinian Territory'],
  [ 'Panama',  'Panama'],
  [ 'Papua New Guinea',  'Papua New Guinea'],
  [ 'Paraguay',  'Paraguay'],
  [ 'Peru',  'Peru'],
  [ 'Philippines',  'Philippines'],
  [ 'Pitcairn',  'Pitcairn'],
  [ 'Poland',  'Poland'],
  [ 'Portugal',  'Portugal'],
  [ 'Puerto Rico',  'Puerto Rico'],
  [ 'Qatar',  'Qatar'],
  [ 'Reunion',  'Reunion'],
  [ 'Romania',  'Romania'],
  [ 'Russian Federation',  'Russian Federation'],
  [ 'Rwanda',  'Rwanda'],
  [ 'Saint Helena',  'Saint Helena'],
  [ 'Saint Kitts and Nevis',  'Saint Kitts and Nevis'],
  [ 'Saint Lucia',  'Saint Lucia'],
  [ 'Saint Pierre and Miquelon',  'Saint Pierre and Miquelon'],
  [ 'Saint Vincent and the Grenadines',  'Saint Vincent and the Grenadines'],
  [ 'Samoa',  'Samoa'],
  [ 'San Marino',  'San Marino'],
  [ 'Sao Tome and Principe',  'Sao Tome and Principe'],
  [ 'Saudi Arabia',  'Saudi Arabia'],
  [ 'Senegal',  'Senegal'],
  [ 'Serbia and Montenegro',  'Serbia and Montenegro'],
  [ 'Seychelles',  'Seychelles'],
  [ 'Sierra Leone',  'Sierra Leone'],
  [ 'Singapore',  'Singapore'],
  [ 'Slovakia',  'Slovakia'],
  [ 'Slovenia',  'Slovenia'],
  [ 'Solomon Islands',  'Solomon Islands'],
  [ 'Somalia',  'Somalia'],
  [ 'South Africa',  'South Africa'],
  [ 'South Georgia and the South Sandwich Islands',  'South Georgia and the South Sandwich Islands'],
  [ 'Spain',  'Spain'],
  [ 'Sri Lanka',  'Sri Lanka'],
  [ 'Sudan',  'Sudan'],
  [ 'Suriname',  'Suriname'],
  [ 'Svalbard and Jan Mayen',  'Svalbard and Jan Mayen'],
  [ 'Swaziland',  'Swaziland'],
  [ 'Sweden',  'Sweden'],
  [ 'Switzerland',  'Switzerland'],
  [ 'Syrian Arab Republic',  'Syrian Arab Republic'],
  [ 'Taiwan',  'Taiwan'],
  [ 'Tajikistan',  'Tajikistan'],
  [ 'Tanzania',  'Tanzania'],
  [ 'Thailand',  'Thailand'],
  [ 'Timor-Leste',  'Timor-Leste'],
  [ 'Togo',  'Togo'],
  [ 'Tokelau',  'Tokelau'],
  [ 'Tonga',  'Tonga'],
  [ 'Trinidad and Tobago',  'Trinidad and Tobago'],
  [ 'Tunisia',  'Tunisia'],
  [ 'Turkey',  'Turkey'],
  [ 'Turkmenistan',  'Turkmenistan'],
  [ 'Turks and Caicos Islands',  'Turks and Caicos Islands'],
  [ 'Tuvalu',  'Tuvalu'],
  [ 'Uganda',  'Uganda'],
  [ 'Ukraine',  'Ukraine'],
  [ 'United Arab Emirates',  'United Arab Emirates'],
  [ 'United Kingdom',  'United Kingdom'],
  [ 'United States',  'United States'],
  [ 'United States Minor Outlying Islands',  'United States Minor Outlying Islands'],
  [ 'Uruguay',  'Uruguay'],
  [ 'Uzbekistan',  'Uzbekistan'],
  [ 'Vanuatu',  'Vanuatu'],
  [ 'Venezuela',  'Venezuela'],
  [ 'Viet Nam',  'Viet Nam'],
  [ 'Virgin Islands', 'Virgin Islands'],
  [ 'Wallis and Futuna',  'Wallis and Futuna'],
  [ 'Western Sahara',  'Western Sahara'],
  [ 'Yemen',  'Yemen'],
  [ 'Zambia',  'Zambia'],
  [ 'Zimbabwe',  'Zimbabwe']
]), {}, {class: "form-control"} %>
<%= f.label :description, {class: "form-group"}  %>
<%= f.text_area :description, {class: "form-control"} %>
<br>
<p><%= f.submit nil, {class: "btn btn-default"} %></p>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1>Edit: <%= @product.name %></h1>

  <%= render "form" %>
</div>

app/views/products/index.html.erb
<div class="jumbotron" id="welcome">
  <div class="container">
    <a name="welcome"><h1>Welcome</h1></a>
    <h1>Mario's Speciality Food Products</h1>
  </div>
</div>

<div class="jumbotron" id="about">
  <div class="container">
    <a name="about"><h1>About Marios</h1></a>
    <p><em>Marios</em> was founded in 1983 on Hawthorne Boulevard in Southeast Portland, and over the years has built a reputation as one of the great European-style markets in the United States.</p>
    <p><em>Marios</em> is famous for it’s housemade fresh pastas (extruded, sheet and ravioli) using the highest quality Northwest-grown wheat and eggs. Additionally, our in-house kitchen prepares fresh pasta sauces, and an array of delicious prepared foods.</p>
    <p>But <em>Marios</em> isn't just about pasta. There is also a revered selection of Mediterranean wines (with a strong focus on Italian), cheese cases unparalleled in the Northwest, and extraordinary food products sourced locally, regionally, nationally and internationally.</p>
  </div>
</div>

<div class="jumbotron" id="scopes">
  <div class="container">
    <div class="row">
      <div class="col-sm-6" id="popular">
      <a name="popular"><h2>Check out the Most Talked about Product:</h2></a>
        <ul>
          <% @products.mostReviews.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-sm-6" id="new">
        <a name="new"><h2>These products have recently been added:</h2></a>
        <ul>
          <% @products.mostRecent.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron" id="products">
  <div class="container">
    <div class="row">
      <div class="col-sm-6" id="products">
        <a name="products"><h1>Products</h1></a>
        <ul>
          <% @products.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
        <br>
        <%= link_to "Add a New Product", new_product_path, {class: 'btn btn-default'}%>
      </div>
      <div class="col-sm-6" id="local">
        <h1>Local Products</h1>
        <ul>
          <% @products.localProducts.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
        <%= image_tag "wine.jpg", {id: 'wine'} %>
      </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>Add a New Product</h1>

  <%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="well">
    <h1>Product Name: <%= @product.name %></h1>
    <br>
    <p><strong>Country: </strong><%= @product.country %></p>
    <p><strong>Cost:</strong> $ <%= @product.cost %></p>
    <br>
    <h4>Description:</h4>
    <p><%= @product.description %></p>

    <%= link_to "Edit this Product", edit_product_path(@product) %> | <%= link_to "Delete this Product", product_path(@product),
                                        :data => { :confirm => "Are you sure you want to remove this product from the system?",
                                        :method => "delete"} %>
  </div>
  <hr>
  <% if @product.reviews.any?%>
    <h3>Reviews</h3>
    <% @product.reviews.each do |review|  %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Author:</strong> <%= review.author %> | <strong>Created on:</strong> <%= review.created_at %> | <strong>Updated on:</strong> <%= review.updated_at %>
        </div>

        <div class="panel-body">
          <strong>Rating:</strong> <%= review.rating %>
          <p><%= review.content_body %></p>
          <br>
          <%= link_to "Edit Review", edit_product_review_path(@product, review) %> |
          <%= link_to "Delete Review", product_review_path(@product, review),
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </div>
      </div>
    <% end %>

  <% else %>
    <p>There are no reviews yet, be the first!</p>
  <% end %>
  <%= link_to "Add a Review", new_product_review_path(@product), {class: 'btn btn-default'} %>

</div>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author, {class: "form-group"}, id: 'Author'  %>
  <%= f.text_field :author, {class: "form-control"} %>
  <%= f.label :review, {class: "form-group"}, id: 'Review'  %>
  <%= f.text_area :content_body, {class: "form-control"} %>
  <br>
  <%= f.label :rating, {class: "form-group"}, id: 'Rating'  %>
  <%= f.number_field :rating, in: 1..5, step: 1%>
<br>
<p><%= f.submit nil, {class: "btn btn-default"} %></p>
<% end %>

app/views/reviews/edit.html.erb
<div class="container">
  <h1>Edit Review</h1>

  <%= render "form" %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add a New Review</h1>

  <%= render "form" %>
</div>